<?php

class Bazaar extends IDBTable {
	public function __construct($db) {
		parent::__construct($db);
        $this->tablename        = 'JOIN ITM_IMAGES ON ITM_IMAGES.ITM_CD = PRODUCT_MV.ITM_CD';
		$this->dbcolumns        = array(
                                            'META_TITLE' => 'META_TITLE',
                                            'MOTION_MECH_TYPE' => 'MOTION_MECH_TYPE',
                                            'MOTION_MECH_TYPE2' => 'MOTION_MECH_TYPE2',
                                            'MOTION_TYPE' => 'MOTION_TYPE',
                                            'MOTION_TYPE2' => 'MOTION_TYPE2',
                                            'NEW' => 'NEW',
                                            'PARENT_CATEGORY1' => 'PARENT_CATEGORY1',
                                            'PARENT_CATEGORY2' => 'PARENT_CATEGORY2',
                                            'PORT' => 'PORT',
                                            'POWER_TYPE' => 'POWER_TYPE',
                                            'PREMIUM_MATTRESS' => 'PREMIUM_MATTRESS',
                                            'PRODUCT_CARE' => 'PRODUCT_CARE',
                                            'PRODUCT_FEATURES' => 'PRODUCT_FEATURES',
                                            'PRODUCT_FINISH' => 'PRODUCT_FINISH',
                                            'PRODUCT_GROUP' => 'PRODUCT_GROUP',
                                            'PRODUCT_NAME' => 'PRODUCT_NAME',
                                            'PRODUCT_PAGE' => 'PRODUCT_PAGE',
                                            'PROD_DES' => 'PROD_DES',
                                            'RECLINERS' => 'RECLINERS',
                                            'REVERSIBLE_CHAISE' => 'REVERSIBLE_CHAISE',
                                            'ROMANCE_DES' => 'ROMANCE_DES',
                                            'ROOM_CATEGORY' => 'ROOM_CATEGORY',
                                            'SAFEGUARD' => 'SAFEGUARD',
                                            'SAFEGUARD_TYPE' => 'SAFEGUARD_TYPE',
                                            'SEAT_BACK_COMP' => 'SEAT_BACK_COMP',
                                            'SEAT_BACK_HEIGHT' => 'SEAT_BACK_HEIGHT',
                                            'SEAT_BACK_TYPE' => 'SEAT_BACK_TYPE',
                                            'SEAT_COMP' => 'SEAT_COMP',
                                            'SEAT_DEPTH' => 'SEAT_DEPTH',
                                            'SEAT_SUPPORT' => 'SEAT_SUPPORT',
                                            'SEAT_TYPE' => 'SEAT_TYPE',
                                            'SIZE_CLASS' => 'SIZE_CLASS',
                                            'SLEEPER_SOFA' => 'SLEEPER_SOFA',
                                            'SMART' => 'SMART',
                                            'SPECIAL_NOTES' => 'SPECIAL_NOTES',
                                            'STORAGE_COMPARTMENT' => 'STORAGE_COMPARTMENT',
                                            'STORAGE_TYPE' => 'STORAGE_TYPE',
                                            'SUSPENSION_SYS' => 'SUSPENSION_SYS',
                                            'TABLE_BASE' => 'TABLE_BASE',
                                            'TABLE_HEIGHT_CLASS' => 'TABLE_HEIGHT_CLASS',
                                            'TABLE_SHAPE' => 'TABLE_SHAPE',
                                            'TABLE_TOP_MTRL' => 'TABLE_TOP_MTRL',
                                            'THROW_PILLOWS' => 'THROW_PILLOWS',
                                            'TOP_TYPE' => 'TOP_TYPE',
                                            'TV_SIZE' => 'TV_SIZE',
                                            'PRODUCT_MV_UPDATED_AT' => 'PRODUCT_MV_UPDATED_AT',
                                            'USB_PORTS' => 'USB_PORTS',
                                            'VE_CD' => 'VE_CD',
                                            'VENDOR' => 'VENDOR',
                                            'VENDOR_TYPE' => 'VENDOR_TYPE',
                                            'VENDOR_CAT' => 'VENDOR_CAT',
                                            'VOL' => 'VOL',
                                            'WALL_HUG' => 'WALL_HUG',
                                            'WARRANTY' => 'WARRANTY',
                                            'WEB_LIVE_DATE' => 'WEB_LIVE_DATE',
                                            'WEIGHT' => 'WEIGHT',
                                            'WIDTH' => 'WIDTH',
                                            'WIRELESS_CHARGING' => 'WIRELESS_CHARGING',
                                            'WIRELESS_REMOTE' => 'WIRELESS_REMOTE',
                                            'ZIPPER' => 'ZIPPER',
                                            'ITM_CD' => 'ITM_CD',
                                            'MJR_CD' => 'MJR_CD',
                                            'MJR_DES' => 'MJR_DES',
                                            'MNR_CD' => 'MNR_CD',
                                            'MNR_DES' => 'MNR_DES',
                                            'PRDGRP_ID' => 'PRDGRP_ID',
                                            'STYLE_CD' => 'STYLE_CD',
                                            'ITM_TP_CD' => 'ITM_TP_CD',
                                            'ECOMM_STATUS' => 'ECOMM_STATUS',
                                            'VSN' => 'VSN',
                                            'BRAND' => 'BRAND',
                                            'CATEGORIES' => 'CATEGORIES',
                                            'WEB_PRODUCT_GROUP' => 'WEB_PRODUCT_GROUP',
                                            'SUMMARY' => 'SUMMARY',
                                            'ECOMM_DES' => 'ECOMM_DES',
                                            'PUDEL' => 'PUDEL',
                                            'ALT_DES' => 'ALT_DES',
                                            'ADJ_FOUNDATION' => 'ADJ_FOUNDATION',
                                            'ADJ_FOUND_FOOT_LIFT' => 'ADJ_FOUND_FOOT_LIFT',
                                            'ADJ_FOUND_HEAD_LIFT' => 'ADJ_FOUND_HEAD_LIFT',
                                            'ARM_HEIGHT' => 'ARM_HEIGHT',
                                            'ARM_TYPE' => 'ARM_TYPE',
                                            'ARM_WIDTH' => 'ARM_WIDTH',
                                            'ASSEMBLY' => 'ASSEMBLY',
                                            'ASSEMBLY_TIME' => 'ASSEMBLY_TIME',
                                            'BASE' => 'BASE',
                                            'BED_FOUND_NEED' => 'BED_FOUND_NEED',
                                            'BED_SIZE' => 'BED_SIZE',
                                            'BED_TYPE' => 'BED_TYPE',
                                            'BLUETOOTH' => 'BLUETOOTH',
                                            'BOX_DEPTH' => 'BOX_DEPTH',
                                            'BOX_HEIGHT' => 'BOX_HEIGHT',
                                            'BOX_WIDTH' => 'BOX_WIDTH',
                                            'BULK_TP_ITM' => 'BULK_TP_ITM',
                                            'CHEMICAL1' => 'CHEMICAL1',
                                            'CHEMICAL2' => 'CHEMICAL2',
                                            'CHILD_CATEGORY1' => 'CHILD_CATEGORY1',
                                            'CHILD_CATEGORY2' => 'CHILD_CATEGORY2',
                                            'CLOSE_DT_NORTH' => 'CLOSE_DT_NORTH',
                                            'CLOSE_DT_SOUTH' => 'CLOSE_DT_SOUTH',
                                            'COLOR' => 'COLOR',
                                            'COLOR_FAMILY' => 'COLOR_FAMILY',
                                            'COLOR_FAMILY2' => 'COLOR_FAMILY2',
                                            'COMP_ADJ_FOUND' => 'COMP_ADJ_FOUND',
                                            'CONSOLE' => 'CONSOLE',
                                            'CORD_MGMT_HOLES' => 'CORD_MGMT_HOLES',
                                            'COUNTRY' => 'COUNTRY',
                                            'CREATE_DT' => 'CREATE_DT',
                                            'PRODUCT_MV_CREATED_AT' => 'PRODUCT_MV_CREATED_AT',
                                            'CUP' => 'CUP',
                                            'CUSTOM_SKU' => 'CUSTOM_SKU',
                                            'DEPTH' => 'DEPTH',
                                            'DES' => 'DES',
                                            'DESIGN1' => 'DESIGN1',
                                            'DESIGN2' => 'DESIGN2',
                                            'DRAWERS' => 'DRAWERS',
                                            'DRAWER_COMP' => 'DRAWER_COMP',
                                            'DRAWER_GLIDE' => 'DRAWER_GLIDE',
                                            'DRAWER_GLIDE2' => 'DRAWER_GLIDE2',
                                            'DRAWER_JOINT' => 'DRAWER_JOINT',
                                            'DROP_CD_NORTH' => 'DROP_CD_NORTH',
                                            'DROP_CD_SOUTH' => 'DROP_CD_SOUTH',
                                            'DROP_DT_NORTH' => 'DROP_DT_NORTH',
                                            'DROP_DT_SOUTH' => 'DROP_DT_SOUTH',
                                            'ECOMM_IMG_STATUS' => 'ECOMM_IMG_STATUS',
                                            'ECOMM_NOTES' => 'ECOMM_NOTES',
                                            'ECOMM_ROMANCE_LANG_STATUS' => 'ECOMM_ROMANCE_LANG_STATUS',
                                            'FABRIC_TYPE' => 'FABRIC_TYPE',
                                            'FACING' => 'FACING',
                                            'FLR_CLEARANCE_HT' => 'FLR_CLEARANCE_HT',
                                            'FOAM_DENSITY' => 'FOAM_DENSITY',
                                            'FRAME' => 'FRAME',
                                            'FRAME2' => 'FRAME2',
                                            'GOOGLE_PRODUCT_CATEGORIES' => 'GOOGLE_PRODUCT_CATEGORIES',
                                            'HEIGHT' => 'HEIGHT',
                                            'IMAGE' => 'IMAGE',
                                            'IMAGE360' => 'IMAGE360',
                                            'INCOTERM' => 'INCOTERM',
                                            'ITEMS_IN_BOX' => 'ITEMS_IN_BOX',
                                            'ITM_STATE' => 'ITM_STATE',
                                            'JOINT' => 'JOINT',
                                            'LADDER_INCL' => 'LADDER_INCL',
                                            'LEADTIME' => 'LEADTIME',
                                            'LEAD_TIME_NORTH' => 'LEAD_TIME_NORTH',
                                            'LEAD_TIME_SOUTH' => 'LEAD_TIME_SOUTH',
                                            'LEAF' => 'LEAF',
                                            'LEAF_SIZE' => 'LEAF_SIZE',
                                            'LEAF_TYPE' => 'LEAF_TYPE',
                                            'LEG_COLOR' => 'LEG_COLOR',
                                            'LEG_HEIGHT' => 'LEG_HEIGHT',
                                            'LEG_MATERIAL' => 'LEG_MATERIAL',
                                            'LEG_TYPE' => 'LEG_TYPE',
                                            'LIGHTING' => 'LIGHTING',
                                            'LOCATION' => 'LOCATION',
                                            'MATERIAL' => 'MATERIAL',
                                            'MATTRESS_COMFORT_LVL' => 'MATTRESS_COMFORT_LVL',
                                            'MATTRESS_INCL' => 'MATTRESS_INCL',
                                            'MATTRESS_TYPE' => 'MATTRESS_TYPE',
                                            'MAX_WEIGHT' => 'MAX_WEIGHT',
                                            'MERCH_NAME' => 'MERCH_NAME',
                                            'MERCH_VISIBILITY' => 'MERCH_VISIBILITY',
                                            'META_DES' => 'META_DES',
                                            'META_KEYWORD' => 'META_KEYWORD',
                                            'DES' => 'DES',
                                            'ALT_DES' => 'ALT_DES',
                                            'ID' => 'ID',
                                            'ITM_IMAGES_UPDATED_AT' => 'ITM_IMAGES_UPDATED_AT',
                                            'ITM_IMAGES_CREATED_AT' => 'ITM_IMAGES_CREATED_AT',
                                            'TYPE' => 'TYPE',
                                            'NAME' => 'NAME',
                                            'URL' => 'URL',
                                            'SEQ_NO' => 'SEQ_NO',

									);

		$this->dbcolumns_date	 = array(
										  'ITM_IMAGES_UPDATED_AT'
										, 'ITM_IMAGES_CREATED_AT'
										, 'PRODUCT_MV_CREATED_AT'
										, 'PRODUCT_MV_UPDATE_AT'
										);

        $this->dbcolumns_function = array( 
                                            "ITM_IMAGES_CREATED_AT"  => "ITM_IMAGES.CREATED_AT ITM_IMAGES_CREATED_AT"  
                                        ,   "PRODUCT_MV_CREATED_AT"  => "PRODUCT_MV.CREATED_AT PRODUCT_MV_CREATED_AT"  
                                        ,   "PRODUCT_MV_UPDATE_AT"  => "PRODUCT_MV.UPDATED_AT PRODUCT_MV_UPDATED_AT"  
                                        ,   "ITM_IMAGES_UPDATED_AT"  => "ITM_IMAGES.UPDATED_AT ITM_IMAGES_UPDATED_AT"  
        );  

		$this->errorMsg 			= "";

	}
}

?>
